dist: bionic

language: go

go:
  - 1.12
  - 1.13

cache:
  directories:
    - $HOME/go/src

env:
  - GO111MODULE=on GOBIN=$HOME

matrix:
  fast_finish: true

before_install:
  - go get -v golang.org/x/lint/golint
  - go get -v golang.org/x/tools/cmd/goimports

install:
  - go mod download
  - go build -v github.com/src-d/go-asdf

script:
  - export PATH=$PATH:$HOME
  - fmt_warns=$(gofmt -s -l .)
  - if [ ! -z "$fmt_warns" ]; then echo "$fmt_warns"; exit 1; fi
  - import_warns=$(goimports -l .)
  - if [ ! -z "$import_warns" ]; then echo "$import_warns"; exit 1; fi
  - go vet ./...
  - lint_warns=$(golint ./... | grep -v vendor/) || true
  - if [ ! -z "$lint_warns" ]; then echo "$lint_warns"; exit 1; fi
  - go test -coverprofile=coverage.txt -covermode=count -tags gorgonia github.com/src-d/go-asdf/...

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
